insert into public.fragments_exercises (id, name_movement, name_exercise, position, repetition)
values  (37, 'alternate arm curl', 'alternate arm curl 10 repetition', 0, 10),
        (38, 'push up', 'push up 10 repetition', 0, 10),
        (39, 'stretching lumbar', 'upper body stretching', 2, 1),
        (40, 'streching backbones', 'upper body stretching', 1, 1),
        (41, 'streching arms', 'upper body stretching', 0, 1),
        (42, 'sheathing', 'sheathing 1 minute', 1, 10),
        (43, 'sheathing', 'sheathing 1 minute', 0, 20),
        (44, 'jumping jack', 'big warm up', 0, 20),
        (45, 'knee raise', 'big warm up', 1, 20),
        (46, 'squat extension', 'big warm up', 2, 20),
        (47, 'left arm curl', 'right curl followed by left curl 10 for each', 1, 10),
        (48, 'right arm curl', 'right curl followed by left curl 10 for each', 0, 10),
        (49, 'curl', 'curl 10 repetition', 0, 10),
        (50, 'squat', 'squat 20 repetition', 0, 20),
        (51, 'knee raise', 'knee raise 20 repetition', 0, 20),
        (52, 'abs', 'abs 10 repetition', 0, 10),
        (53, 'jumping jack', 'jumping jack 20 repetition', 0, 20),
        (54, 'squat extension', 'squat extension 20 repetition', 0, 20),
        (55, 'squat extension', 'tabata', 0, 10),
        (56, 'streching backbones', 'tabata', 9, 4),
        (57, 'sheathing', 'tabata', 5, 20),
        (58, 'sheathing', 'tabata', 7, 20),
        (59, 'abs', 'tabata', 3, 5),
        (60, 'push up', 'tabata', 1, 5),
        (61, 'squat', 'tabata', 2, 10),
        (62, 'jumping jack', 'tabata', 4, 20),
        (63, 'sheathing', 'tabata', 6, 20),
        (64, 'streching arms', 'tabata', 8, 4),
        (65, 'stretching lumbar', 'tabata', 10, 4);